[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.71"
bytes = "1.2.1"
bzip2 = "0.4.4"
flate2 = "1.0.22"
futures = "0.3.19"
futures-util = "0.3.21"
reqwest = { version = "0.11.18", features = ["blocking", "json", "stream", "rustls-tls"], default-features = false, optional = true }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
tar = "0.4.38"
tokio = { version = "1.28.2", features = ["rt", "rt-multi-thread"] }
xz2 = "0.1.6"

[features]
default = []
network = ["dep:reqwest"]
